# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/laser_control.ui'
#
# Created: Sun Mar 31 15:52:08 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_LaserControl(object):
    def setupUi(self, LaserControl):
        LaserControl.setObjectName(_fromUtf8("LaserControl"))
        LaserControl.setWindowModality(QtCore.Qt.NonModal)
        LaserControl.resize(320, 415)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LaserControl.sizePolicy().hasHeightForWidth())
        LaserControl.setSizePolicy(sizePolicy)
        LaserControl.setMinimumSize(QtCore.QSize(320, 415))
        LaserControl.setMaximumSize(QtCore.QSize(367, 480))
        LaserControl.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        LaserControl.setAcceptDrops(False)
        LaserControl.setDocumentMode(False)
        LaserControl.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(LaserControl)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.Movements = QtGui.QGroupBox(self.centralwidget)
        self.Movements.setGeometry(QtCore.QRect(10, 20, 111, 101))
        self.Movements.setStyleSheet(_fromUtf8(""))
        self.Movements.setFlat(True)
        self.Movements.setObjectName(_fromUtf8("Movements"))
        self.gridLayout = QtGui.QGridLayout(self.Movements)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.leftButton = QtGui.QPushButton(self.Movements)
        self.leftButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrow/icons/left.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leftButton.setIcon(icon)
        self.leftButton.setCheckable(False)
        self.leftButton.setAutoRepeat(False)
        self.leftButton.setObjectName(_fromUtf8("leftButton"))
        self.gridLayout.addWidget(self.leftButton, 1, 0, 1, 1)
        self.downButton = QtGui.QPushButton(self.Movements)
        self.downButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.downButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrow/icons/down.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downButton.setIcon(icon1)
        self.downButton.setCheckable(False)
        self.downButton.setAutoRepeat(False)
        self.downButton.setObjectName(_fromUtf8("downButton"))
        self.gridLayout.addWidget(self.downButton, 2, 1, 1, 1)
        self.upButton = QtGui.QPushButton(self.Movements)
        self.upButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.upButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrow/icons/up.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upButton.setIcon(icon2)
        self.upButton.setCheckable(False)
        self.upButton.setAutoRepeat(False)
        self.upButton.setObjectName(_fromUtf8("upButton"))
        self.gridLayout.addWidget(self.upButton, 0, 1, 1, 1)
        self.rightButton = QtGui.QPushButton(self.Movements)
        self.rightButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rightButton.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrow/icons/right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rightButton.setIcon(icon3)
        self.rightButton.setCheckable(False)
        self.rightButton.setAutoRepeat(False)
        self.rightButton.setObjectName(_fromUtf8("rightButton"))
        self.gridLayout.addWidget(self.rightButton, 1, 2, 1, 1)
        self.Positioning = QtGui.QGroupBox(self.centralwidget)
        self.Positioning.setGeometry(QtCore.QRect(130, 20, 191, 101))
        self.Positioning.setObjectName(_fromUtf8("Positioning"))
        self.gridLayout_2 = QtGui.QGridLayout(self.Positioning)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.posVertical = QtGui.QLineEdit(self.Positioning)
        self.posVertical.setReadOnly(False)
        self.posVertical.setObjectName(_fromUtf8("posVertical"))
        self.gridLayout_2.addWidget(self.posVertical, 2, 1, 1, 1)
        self.label_Vertical = QtGui.QLabel(self.Positioning)
        self.label_Vertical.setObjectName(_fromUtf8("label_Vertical"))
        self.gridLayout_2.addWidget(self.label_Vertical, 2, 0, 1, 1)
        self.label_Horizontal = QtGui.QLabel(self.Positioning)
        self.label_Horizontal.setObjectName(_fromUtf8("label_Horizontal"))
        self.gridLayout_2.addWidget(self.label_Horizontal, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)
        self.posHorizontal = QtGui.QLineEdit(self.Positioning)
        self.posHorizontal.setText(_fromUtf8(""))
        self.posHorizontal.setReadOnly(False)
        self.posHorizontal.setObjectName(_fromUtf8("posHorizontal"))
        self.gridLayout_2.addWidget(self.posHorizontal, 1, 1, 1, 1)
        self.Laser = QtGui.QGroupBox(self.centralwidget)
        self.Laser.setGeometry(QtCore.QRect(10, 130, 141, 51))
        self.Laser.setAutoFillBackground(False)
        self.Laser.setCheckable(False)
        self.Laser.setObjectName(_fromUtf8("Laser"))
        self.laserOn = QtGui.QRadioButton(self.Laser)
        self.laserOn.setGeometry(QtCore.QRect(10, 20, 50, 22))
        self.laserOn.setObjectName(_fromUtf8("laserOn"))
        self.laserOff = QtGui.QRadioButton(self.Laser)
        self.laserOff.setGeometry(QtCore.QRect(70, 20, 54, 22))
        self.laserOff.setChecked(True)
        self.laserOff.setObjectName(_fromUtf8("laserOff"))
        self.Status = QtGui.QGroupBox(self.centralwidget)
        self.Status.setGeometry(QtCore.QRect(140, 130, 171, 81))
        self.Status.setObjectName(_fromUtf8("Status"))
        self.status_frame = QtGui.QFrame(self.Status)
        self.status_frame.setGeometry(QtCore.QRect(10, 20, 161, 31))
        self.status_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.status_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.status_frame.setObjectName(_fromUtf8("status_frame"))
        self.text_status = QtGui.QTextEdit(self.status_frame)
        self.text_status.setGeometry(QtCore.QRect(0, 0, 161, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.text_status.setFont(font)
        self.text_status.setReadOnly(True)
        self.text_status.setObjectName(_fromUtf8("text_status"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 120, 301, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 210, 301, 171))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_config = QtGui.QWidget()
        self.tab_config.setObjectName(_fromUtf8("tab_config"))
        self.confMode = QtGui.QCheckBox(self.tab_config)
        self.confMode.setGeometry(QtCore.QRect(10, 10, 170, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.confMode.setFont(font)
        self.confMode.setObjectName(_fromUtf8("confMode"))
        self.textEdit = QtGui.QTextEdit(self.tab_config)
        self.textEdit.setEnabled(True)
        self.textEdit.setGeometry(QtCore.QRect(0, 40, 301, 81))
        self.textEdit.setToolTip(_fromUtf8(""))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.Reconfigure = QtGui.QGroupBox(self.tab_config)
        self.Reconfigure.setGeometry(QtCore.QRect(10, 20, 281, 101))
        self.Reconfigure.setCheckable(True)
        self.Reconfigure.setChecked(False)
        self.Reconfigure.setObjectName(_fromUtf8("Reconfigure"))
        self.redef_1 = QtGui.QCheckBox(self.Reconfigure)
        self.redef_1.setGeometry(QtCore.QRect(50, 30, 191, 22))
        self.redef_1.setCheckable(True)
        self.redef_1.setAutoExclusive(True)
        self.redef_1.setTristate(False)
        self.redef_1.setObjectName(_fromUtf8("redef_1"))
        self.redef_2 = QtGui.QCheckBox(self.Reconfigure)
        self.redef_2.setGeometry(QtCore.QRect(50, 50, 191, 22))
        self.redef_2.setAutoExclusive(True)
        self.redef_2.setObjectName(_fromUtf8("redef_2"))
        self.redef_3 = QtGui.QCheckBox(self.Reconfigure)
        self.redef_3.setGeometry(QtCore.QRect(50, 70, 191, 22))
        self.redef_3.setAutoExclusive(True)
        self.redef_3.setObjectName(_fromUtf8("redef_3"))
        self.tabWidget.addTab(self.tab_config, _fromUtf8(""))
        self.tab_move = QtGui.QWidget()
        self.tab_move.setObjectName(_fromUtf8("tab_move"))
        self.trackMode = QtGui.QCheckBox(self.tab_move)
        self.trackMode.setGeometry(QtCore.QRect(10, 110, 260, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.trackMode.setFont(font)
        self.trackMode.setObjectName(_fromUtf8("trackMode"))
        self.textEdit_2 = QtGui.QTextEdit(self.tab_move)
        self.textEdit_2.setGeometry(QtCore.QRect(0, 10, 291, 81))
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.tabWidget.addTab(self.tab_move, _fromUtf8(""))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 190, 301, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        LaserControl.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(LaserControl)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_Archivo = QtGui.QMenu(self.menubar)
        self.menu_Archivo.setObjectName(_fromUtf8("menu_Archivo"))
        self.menu_Dispositivo = QtGui.QMenu(self.menubar)
        self.menu_Dispositivo.setObjectName(_fromUtf8("menu_Dispositivo"))
        self.menu_Connect = QtGui.QMenu(self.menu_Dispositivo)
        self.menu_Connect.setObjectName(_fromUtf8("menu_Connect"))
        self.menu_Ayuda = QtGui.QMenu(self.menubar)
        self.menu_Ayuda.setObjectName(_fromUtf8("menu_Ayuda"))
        LaserControl.setMenuBar(self.menubar)
        self.action_Cerrar = QtGui.QAction(LaserControl)
        self.action_Cerrar.setObjectName(_fromUtf8("action_Cerrar"))
        self.action_Iniciar = QtGui.QAction(LaserControl)
        self.action_Iniciar.setObjectName(_fromUtf8("action_Iniciar"))
        self.action_Detener = QtGui.QAction(LaserControl)
        self.action_Detener.setEnabled(False)
        self.action_Detener.setObjectName(_fromUtf8("action_Detener"))
        self.action_Desconectar = QtGui.QAction(LaserControl)
        self.action_Desconectar.setEnabled(False)
        self.action_Desconectar.setObjectName(_fromUtf8("action_Desconectar"))
        self.actionAcerca_de = QtGui.QAction(LaserControl)
        self.actionAcerca_de.setObjectName(_fromUtf8("actionAcerca_de"))
        self.actionCargar = QtGui.QAction(LaserControl)
        self.actionCargar.setObjectName(_fromUtf8("actionCargar"))
        self.actionGuardar_configuraci_n = QtGui.QAction(LaserControl)
        self.actionGuardar_configuraci_n.setObjectName(_fromUtf8("actionGuardar_configuraci_n"))
        self.actionCargar_configuraci_n = QtGui.QAction(LaserControl)
        self.actionCargar_configuraci_n.setObjectName(_fromUtf8("actionCargar_configuraci_n"))
        self.action_Recalibrar = QtGui.QAction(LaserControl)
        self.action_Recalibrar.setEnabled(False)
        self.action_Recalibrar.setObjectName(_fromUtf8("action_Recalibrar"))
        self.action_Refresh = QtGui.QAction(LaserControl)
        self.action_Refresh.setObjectName(_fromUtf8("action_Refresh"))
        self.menu_Archivo.addAction(self.action_Cerrar)
        self.menu_Connect.addAction(self.action_Refresh)
        self.menu_Connect.addSeparator()
        self.menu_Dispositivo.addAction(self.menu_Connect.menuAction())
        self.menu_Dispositivo.addAction(self.action_Desconectar)
        self.menu_Dispositivo.addSeparator()
        self.menu_Dispositivo.addAction(self.action_Recalibrar)
        self.menu_Ayuda.addAction(self.actionAcerca_de)
        self.menubar.addAction(self.menu_Archivo.menuAction())
        self.menubar.addAction(self.menu_Dispositivo.menuAction())
        self.menubar.addAction(self.menu_Ayuda.menuAction())

        self.retranslateUi(LaserControl)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.action_Cerrar, QtCore.SIGNAL(_fromUtf8("triggered()")), LaserControl.close)
        QtCore.QMetaObject.connectSlotsByName(LaserControl)
        LaserControl.setTabOrder(self.upButton, self.rightButton)
        LaserControl.setTabOrder(self.rightButton, self.downButton)
        LaserControl.setTabOrder(self.downButton, self.leftButton)
        LaserControl.setTabOrder(self.leftButton, self.posHorizontal)
        LaserControl.setTabOrder(self.posHorizontal, self.posVertical)
        LaserControl.setTabOrder(self.posVertical, self.laserOn)
        LaserControl.setTabOrder(self.laserOn, self.laserOff)
        LaserControl.setTabOrder(self.laserOff, self.tabWidget)
        LaserControl.setTabOrder(self.tabWidget, self.confMode)
        LaserControl.setTabOrder(self.confMode, self.textEdit)
        LaserControl.setTabOrder(self.textEdit, self.textEdit_2)
        LaserControl.setTabOrder(self.textEdit_2, self.trackMode)
        LaserControl.setTabOrder(self.trackMode, self.text_status)

    def retranslateUi(self, LaserControl):
        LaserControl.setWindowTitle(QtGui.QApplication.translate("LaserControl", "Laser Control", None, QtGui.QApplication.UnicodeUTF8))
        self.Movements.setTitle(QtGui.QApplication.translate("LaserControl", "Move", None, QtGui.QApplication.UnicodeUTF8))
        self.Positioning.setTitle(QtGui.QApplication.translate("LaserControl", "Current position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Vertical.setText(QtGui.QApplication.translate("LaserControl", "Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Horizontal.setText(QtGui.QApplication.translate("LaserControl", "Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.Laser.setTitle(QtGui.QApplication.translate("LaserControl", "Laser", None, QtGui.QApplication.UnicodeUTF8))
        self.laserOn.setText(QtGui.QApplication.translate("LaserControl", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.laserOff.setText(QtGui.QApplication.translate("LaserControl", "Off", None, QtGui.QApplication.UnicodeUTF8))
        self.Status.setTitle(QtGui.QApplication.translate("LaserControl", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.text_status.setHtml(QtGui.QApplication.translate("LaserControl", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">References: 0/2</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.confMode.setText(QtGui.QApplication.translate("LaserControl", "Configuration mode", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit.setHtml(QtGui.QApplication.translate("LaserControl", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">With this option activated, the &quot;goto&quot;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">commands received from Stellarium will</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">be send to the device in order to sets in order</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">each one of the </span><span style=\" font-weight:600; font-style:italic;\">two reference objects</span><span style=\" font-style:italic;\">.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Reconfigure.setTitle(QtGui.QApplication.translate("LaserControl", "Redefine reference object:", None, QtGui.QApplication.UnicodeUTF8))
        self.redef_1.setText(QtGui.QApplication.translate("LaserControl", "Reference object 1", None, QtGui.QApplication.UnicodeUTF8))
        self.redef_2.setText(QtGui.QApplication.translate("LaserControl", "Reference object 2", None, QtGui.QApplication.UnicodeUTF8))
        self.redef_3.setText(QtGui.QApplication.translate("LaserControl", "Reference object 3", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_config), QtGui.QApplication.translate("LaserControl", "Confituration", None, QtGui.QApplication.UnicodeUTF8))
        self.trackMode.setText(QtGui.QApplication.translate("LaserControl", "Tracking mode", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_2.setHtml(QtGui.QApplication.translate("LaserControl", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">Now you can start to use the device.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-style:italic;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">The laser will points to the equatorial</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">coordinates received from Stellarium.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_move), QtGui.QApplication.translate("LaserControl", "Pointing", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Archivo.setTitle(QtGui.QApplication.translate("LaserControl", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Dispositivo.setTitle(QtGui.QApplication.translate("LaserControl", "&Device", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Connect.setTitle(QtGui.QApplication.translate("LaserControl", "&Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Ayuda.setTitle(QtGui.QApplication.translate("LaserControl", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Cerrar.setText(QtGui.QApplication.translate("LaserControl", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Iniciar.setText(QtGui.QApplication.translate("LaserControl", "&Iniciar", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Detener.setText(QtGui.QApplication.translate("LaserControl", "&Detener", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Desconectar.setText(QtGui.QApplication.translate("LaserControl", "&Desconectar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAcerca_de.setText(QtGui.QApplication.translate("LaserControl", "About ..", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCargar.setText(QtGui.QApplication.translate("LaserControl", "Cargar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGuardar_configuraci_n.setText(QtGui.QApplication.translate("LaserControl", "Guardar en archivo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCargar_configuraci_n.setText(QtGui.QApplication.translate("LaserControl", "Cargar desde archivo", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Recalibrar.setText(QtGui.QApplication.translate("LaserControl", "Recalibrar", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Refresh.setText(QtGui.QApplication.translate("LaserControl", "Refresh Port List", None, QtGui.QApplication.UnicodeUTF8))

import icons_set_rc
